{
 "title": "Web Gateway Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cfDist", "label": "Cloudfront Distribution ID", "query": "*" },
   { "name": "envCsi", "label": "Environment CSI Prefix", "query": "nhs-${env}-cdn" },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   { "name": "env", "label": "Environment", "query": "main" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 }, "options": { "content": "# Web Gateway Service Levels" } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Certficate Expiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "DaysToExpiry",
     "namespace": "AWS/CertificateManager",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 10 }, "options": { "content": "## Traffic" } },
  {
   "title": "Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cloudfront Cache Hit",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*($B/100)", "type": "math" }
   ]
  },
  {
   "title": "WAF Allowed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 12 },
   "targets": [
    {
     "dimensions": { "WebACL": "$envCsi" },
     "metricName": "AllowedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cloudfront Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "WAF Blocked Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 20 },
   "targets": [
    {
     "dimensions": { "WebACL": "$envCsi" },
     "metricName": "BlockedRequests",
     "namespace": "AWS/WAFV2",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 26 }, "options": { "content": "## Latency" } },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 11, "y": 26 }, "options": { "content": "## Errors" } },
  {
   "title": "Cloudfront Origin Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "OriginLatency",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Cloudfront Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "TotalErrorRate",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cloudfront Origin Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "OriginLatency",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  }
 ]
}