{
 "title": "Core Routing Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "prod, int, internal-dev, ref, ref2, refmock, refmock2, staging, uat"
   },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "almDataSrc",
    "label": "Alarm Data Source",
    "query": "computest-cloudwatchalarm-datasource"
   },
   {
    "name": "fifoEnrichmentQueue",
    "query": "comms-${env}-api-stl-enrichment-queue.fifo"
   },
   {
    "name": "fifoEnrichmentDlq",
    "query": "comms-${env}-api-stl-enrichment-dlq.fifo"
   },
   {
    "name": "fifoReEnrichmentQueue",
    "query": "comms-${env}-api-stl-reenrichment-queue.fifo"
   },
   {
    "name": "fifoReEnrichmentDlq",
    "query": "comms-${env}-api-stl-reenrichment-dlq.fifo"
   }
  ]
 },
 "panels": [
  {
   "title": "Composite Alarm Statuses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "region": "eu-west-2" }
   ]
  },
  {
   "title": "Client Requests Queued",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Client Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 4 },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Request Enqueuing Rate (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 4 },
   "targets": [
    { "expression": "$A/300", "type": "math" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 }, "options": { "content": "## Enrichment" } },
  {
   "title": "Enrichment Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$fifoEnrichmentDlq" },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Enrichment PDS HTTP response status (no campaign)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "metricName": "NumberOfMessagesSent",
     "metricQueryType": 1,
     "namespace": "comms-enrichment-metrics",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "comms-enrichment-metrics", "type": "functionParameter" },
        { "name": "client_id", "type": "functionParameter" },
        { "name": "Environment", "type": "functionParameter" },
        { "name": "http_status_code", "type": "functionParameter" },
        { "name": "request_id", "type": "functionParameter" },
        { "name": "sending_group_id", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "http_status_code", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "pds_message_sent", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(pds_message_sent) FROM SCHEMA(\"comms-enrichment-metrics\", client_id, Environment, http_status_code, request_id, sending_group_id) GROUP BY http_status_code",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Enrichment Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "metricName": "NumberOfMessagesSent",
     "metricQueryType": 1,
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fifoEnrichmentQueue" }, "property": { "name": "QueueName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = '$fifoEnrichmentQueue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Re-enrichment Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "metricName": "NumberOfMessagesSent",
     "metricQueryType": 1,
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$fifoReEnrichmentQueue" }, "property": { "name": "QueueName", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = '$fifoReEnrichmentQueue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Reenrichment PDS HTTP response status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "metricName": "NumberOfMessagesSent",
     "metricQueryType": 1,
     "namespace": "comms-reenrichment-metrics",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "comms-reenrichment-metrics", "type": "functionParameter" },
        { "name": "campaign_id", "type": "functionParameter" },
        { "name": "client_id", "type": "functionParameter" },
        { "name": "Environment", "type": "functionParameter" },
        { "name": "http_status_code", "type": "functionParameter" },
        { "name": "request_id", "type": "functionParameter" },
        { "name": "sending_group_id", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "http_status_code", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "pds_message_sent", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(pds_message_sent) FROM SCHEMA(\"comms-reenrichment-metrics\", campaign_id, client_id, Environment, http_status_code, request_id, sending_group_id) GROUP BY http_status_code",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Enrichment Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    { "expression": "$A/60", "type": "math" },
    { "expression": "$B/60", "type": "math" }
   ]
  },
  {
   "title": "Re-enrichment Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "dimensions": { "QueueName": "$fifoReEnrichmentQueue" },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$fifoReEnrichmentQueue" },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "QueueName": "$fifoReEnrichmentDlq" },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "QueueName": "$fifoReEnrichmentQueue" },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Enrichment PDS HTTP response status (campaign)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": { "QueueName": "$fifoEnrichmentQueue" },
     "metricName": "NumberOfMessagesSent",
     "metricQueryType": 1,
     "namespace": "comms-enrichment-metrics",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "comms-enrichment-metrics", "type": "functionParameter" },
        { "name": "campaign_id", "type": "functionParameter" },
        { "name": "client_id", "type": "functionParameter" },
        { "name": "Environment", "type": "functionParameter" },
        { "name": "http_status_code", "type": "functionParameter" },
        { "name": "request_id", "type": "functionParameter" },
        { "name": "sending_group_id", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "groupBy": {
       "expressions": [
        { "property": { "name": "http_status_code", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "pds_message_sent", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(pds_message_sent) FROM SCHEMA(\"comms-enrichment-metrics\", campaign_id, client_id, Environment, http_status_code, request_id, sending_group_id) GROUP BY http_status_code",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 }, "options": { "content": "## NHS App" } },
  {
   "title": "Dispatched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "NHS App Requests Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Callbacks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-callback-queue"
     },
     "label": "NHS App Callbacks Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "NHS App Send Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "Environment": "$env" },
     "label": "Send Errors",
     "metricName": "comms-$env-api-srnl-sendrequests-nhsapp-error-count",
     "namespace": "comms-$env-lambda-errors",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NHS App messages queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "NHS App Send Rate (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "NHS App backlog (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NHS App callbacks processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-callback-queue"
     },
     "label": "Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-callback-queue"
     },
     "label": "Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-callback-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-nhsapp-callback-queue"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "NHS App Expiry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "label": "Poll Expired",
     "metricName": "PollRequestTtlItemsDeleted",
     "namespace": "comms-poll-request-ttl-metrics",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "TableName": "comms-$env-api-stg-comms-requests-with-ttl"
     },
     "label": "TTL Expired",
     "metricName": "TimeToLiveDeletedItemCount",
     "namespace": "AWS/DynamoDB",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 }, "options": { "content": "## Gov.UK Notify" } },
  {
   "title": "Dispatched",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "GUN Messages Dispatched",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Callbacks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "GUN Callbacks Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "NumberOfMessagesDeleted", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "comms-$env-api-stl-send-nhsapp-queue"
         },
         "property": { "name": "QueueName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(NumberOfMessagesDeleted) FROM \"AWS/SQS\" WHERE QueueName = 'comms-$env-api-stl-send-nhsapp-queue'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Gov.UK Notify messages sent (inc letters)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "GUN Messages Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "GUN Messages Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "SMS + email messages queued",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "SMS + Email Send Rate (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "SMS + Email backlog (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Gov UK callbacks processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "GUN Callbacks Queued",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "GUN Callbacks Processed",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-dlq"
     },
     "label": "DLQ",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-govuknotify-callback-queue"
     },
     "label": "Backlog",
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 84 }, "options": { "content": "## Letters" } },
  {
   "title": "Letter Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lpl-render-pdf-queue"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-rol-router-request-letter.fifo"
     },
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letter Count Per Supplier",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lpl-render-pdf-queue"
     },
     "label": "GUN PDF Pipeline",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "label": "HH CSV Pipeline",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "label": "Synertec CSV Pipeline",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-rol-router-request-letter.fifo"
     },
     "label": "Notify Legacy",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letters requests sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lpl-render-pdf-queue"
     },
     "label": "GUN PDF Pipeline",
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "Environment": "$env",
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "label": "HH CSV Pipeline",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "label": "Synertec CSV Pipeline",
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "comms-$env-api-ecl-sftpsend" },
     "label": "HH SFTP Send",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "FunctionName": "comms-$env-api-sftpsendlambda-sftpsendsynertec"
     },
     "label": "Synertec SFTP Send",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-rol-router-request-letter.fifo"
     },
     "label": "Notify Legacy",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letters requests queued",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "virtual_queue_insertion",
     "namespace": "comms-process-queue-updates-lambda-metrics",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letter backlog (letters only sent Sunday - Thursday)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Environment": "$env", "status": "PENDING" },
     "metricName": "queue_length",
     "namespace": "comms-publish-queue-stats-metrics",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": {
       "property": {
        "name": "comms-process-queue-updates-lambda-metrics",
        "type": "string"
       },
       "type": "property"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "virtual_queue_insertion", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$env" }, "property": { "name": "Environment", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(virtual_queue_insertion) FROM \"comms-process-queue-updates-lambda-metrics\" WHERE Environment = '$env'",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 103 }, "options": { "content": "## Router" } },
  {
   "title": "Post-router Throughput (Avg TPS - Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/300", "type": "math" },
    { "expression": "$B/300", "type": "math" },
    { "expression": "$C/300", "type": "math" },
    { "expression": "$D/300", "type": "math" },
    { "expression": "$E/300", "type": "math" }
   ]
  },
  {
   "title": "Routing Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dimensions": {
      "QueueName": "comms-$env-api-lspl-csvbatch-queue"
     },
     "label": "(MBA)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-csvbatchsynertec-queue"
     },
     "label": "(Synertec)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-reenrichment-queue.fifo"
     },
     "label": "(Reenrichment)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-govuknotify-queue"
     },
     "label": "(GUN)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "QueueName": "comms-$env-api-stl-send-nhsapp-queue"
     },
     "label": "(NHS App)",
     "metricName": "NumberOfMessagesDeleted",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Router Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 108 },
   "targets": [
    {
     "dimensions": { "function_name": "comms-$env-api-rol-router" },
     "label": "CPU Time",
     "metricName": "cpu_total_time",
     "namespace": "LambdaInsights",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "FunctionName": "comms-$env-api-rol-router" },
     "label": "Duration",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "FunctionName": "comms-$env-api-rol-router" },
     "label": "Errors",
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}