{
 "title": "Core API Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "prod, int, internal-dev, ref, ref2, refmock, refmock2, staging, uat"
   },
   { "name": "apiName", "query": "comms-${env}-api-oa3-commsapi" },
   {
    "name": "enrichmentQueueName",
    "label": "Enrichment Queue Name",
    "query": "comms-${env}-api-stl-enrichment-queue.fifo"
   },
   {
    "name": "nhsAppSendQueueName",
    "label": "NHS App Queue Name",
    "query": "comms-${env}-api-stl-send-nhsapp-queue"
   },
   {
    "name": "govukSendQueueName",
    "label": "Gov.UK Queue Name",
    "query": "comms-${env}-api-stl-send-govuknotify-queue"
   },
   {
    "name": "hhSftpQueueName",
    "label": "HH SFTP Queue Name",
    "query": "comms-${env}-api-lspl-sftpsend-queue"
   },
   {
    "name": "synertecSftpQueueName",
    "label": "Synertec SFTP Queue Name",
    "query": "comms-${env}-api-stl-sftpsendsynertec-queue"
   },
   {
    "name": "ppSftpQueueName",
    "label": "Precision Proco SFTP Queue Name",
    "query": "comms-${env}-api-stl-sftpsendprecisionproco-queue"
   },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "dlqs",
    "query": "comms-${env}-api-stl-enrichment-dlq.fifo,\ncomms-${env}-api-stl-send-govuknotify-dlq,\ncomms-${env}-api-stl-send-nhsapp-dlq,\ncomms-${env}-api-lspl-sftpsend-dlq,\ncomms-${env}-api-stl-sftpsendsynertec-dlq,\ncomms-${env}-api-stl-sftpsendprecisionproco-dlq"
   }
  ]
 },
 "panels": [
  {
   "title": "Calls to Comms API",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "ApiName": "$apiName" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "PDS Message Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "metricName": "pds_message_sent",
     "metricQueryType": 1,
     "namespace": "comms-enrichment-metrics",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "comms-enrichment-metrics", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "http_status_code", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "pds_message_sent", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(pds_message_sent) FROM \"comms-enrichment-metrics\" GROUP BY http_status_code ORDER BY SUM() ASC",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "PDS TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/300", "type": "math" }
   ]
  },
  {
   "title": "Dead Letter Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/SQS", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "QueueName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        {
         "name": "ApproximateNumberOfMessagesVisible",
         "type": "functionParameter"
        }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(ApproximateNumberOfMessagesVisible) FROM \"AWS/SQS\" GROUP BY QueueName",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 }, "options": { "content": "# Request Enrichment\n" } },
  {
   "title": "Items in Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "ceil($A)", "type": "math" }
   ]
  },
  {
   "title": "Items Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "dimensions": { "QueueName": "$enrichmentQueueName" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 }, "options": { "content": "# NHS App Send Requests\n" } },
  {
   "title": "Items in Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "ceil($A)", "type": "math" }
   ]
  },
  {
   "title": "Items Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 13 },
   "targets": [
    {
     "dimensions": { "QueueName": "$nhsAppSendQueueName" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "options": {
    "content": "# GOV.UK Notify Send Requests\n"
   }
  },
  {
   "title": "Items in Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "ceil($A)", "type": "math" }
   ]
  },
  {
   "title": "Items Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 18 },
   "targets": [
    {
     "dimensions": { "QueueName": "$govukSendQueueName" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 }, "options": { "content": "# SFTP Pipeline - HH" } },
  {
   "title": "Items in Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "ceil($A)", "type": "math" }
   ]
  },
  {
   "title": "Items Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 23 },
   "targets": [
    {
     "dimensions": { "QueueName": "$hhSftpQueueName" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 5, "w": 3, "x": 0, "y": 28 }, "options": { "content": "# SFTP Pipeline - Synertec\n" } },
  {
   "title": "Items in Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "ceil($A)", "type": "math" }
   ]
  },
  {
   "title": "Items Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 28 },
   "targets": [
    {
     "dimensions": { "QueueName": "$synertecSftpQueueName" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
   "options": {
    "content": "# SFTP Pipeline - Precision Proco\n"
   }
  },
  {
   "title": "Items in Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "ceil($A)", "type": "math" }
   ]
  },
  {
   "title": "Items Processed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 33 },
   "targets": [
    {
     "dimensions": { "QueueName": "$ppSftpQueueName" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}