{
 "title": "Supplier API Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   { "name": "env", "label": "Environment", "query": "main" },
   { "name": "envCsi", "label": "Environment CSI Prefix", "query": "nhs-${env}-supapi" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 }, "options": { "content": "# Supplier API Overview" } },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 2 }, "options": { "content": "## Gateway" } },
  {
   "title": "API Gateway Latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "ApiName": "${envCsi}" },
     "label": "Average",
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    },
    {
     "accountId": "all",
     "dimensions": { "ApiName": "${envCsi}" },
     "label": "Maximum",
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "API Gateway Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "ApiName": "${envCsi}" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "API Gateway Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "ApiName": "${envCsi}" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": { "ApiName": "${envCsi}" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 15 }, "options": { "content": "## Queues" } },
  {
   "title": "Letter Updates Queue",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Letter Updates DLQ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "QueueName": "${envCsi}-letter-updates-dlq" },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Letter Status Updates Queue",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Letter Status Updates DLQ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "QueueName": "${envCsi}-letterstatusupdatesqueue-dlq"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "EventPub DLQ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "QueueName": "${envCsi}-eventpub-dlq" },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 23 }, "options": { "content": "## Processing" } },
  {
   "title": "Lambda Invocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" },
    { "expression": "$B/60", "type": "math" },
    { "expression": "$E/60", "type": "math" },
    { "expression": "$G/60", "type": "math" },
    { "expression": "$I/60", "type": "math" },
    { "expression": "$K/60", "type": "math" },
    { "expression": "$M/60", "type": "math" },
    { "expression": "$O/60", "type": "math" },
    { "expression": "$O/60", "type": "math" },
    { "expression": "$S/60", "type": "math" },
    { "expression": "$U/60", "type": "math" }
   ]
  },
  {
   "title": "Lambda Max Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-eventpub" },
     "label": "Event Publisher",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-postmi" },
     "label": "Postmi",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-getletters" },
     "label": "GetLetters",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-patchletter" },
     "label": "PatchLetter",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-authorizer" },
     "label": "Authorizer  ",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-getletter" },
     "label": "GetLetter",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-getstatus" },
     "label": "GetStatus",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-postletters" },
     "label": "PostLetters",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "${envCsi}-letter-updates-transformer"
     },
     "label": "LetterUpdatesTransformer",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-getletterdata" },
     "label": "GetLetterData ",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    },
    {
     "accountId": "all",
     "dimensions": { "FunctionName": "${envCsi}-letterstatusupdate" },
     "label": "LetterStatusUpdate ",
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 43 }, "options": { "content": "## Errors" } },
  {
   "title": "Lambda Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" },
    { "expression": "$B/60", "type": "math" },
    { "expression": "$E/60", "type": "math" },
    { "expression": "$G/60", "type": "math" },
    { "expression": "$I/60", "type": "math" },
    { "expression": "$K/60", "type": "math" },
    { "expression": "$M/60", "type": "math" },
    { "expression": "$O/60", "type": "math" },
    { "expression": "$O/60", "type": "math" },
    { "expression": "$S/60", "type": "math" },
    { "expression": "$U/60", "type": "math" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 54 }, "options": { "content": "## DynamoDB" } },
  {
   "title": "DynamoDB Capacity Units",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DynamoDB Throttled Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 65 }, "options": { "content": "## Kinesis Streams" } },
  {
   "title": "LetterChange - IncomingRecords/IncomingBytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "IncomingRecords",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "IncomingBytes",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "LetterChange - GetRecords.Latency/Getrecords/Records",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "GetRecords.Latency",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "GetRecords.Records",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "LetterChange - GetRecords.Success",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "GetRecords.Success",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "LetterChange - ReadProvisionedThroughputExceeded/WriteProvisionedThroughputExceeded",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "ReadProvisionedThroughputExceeded",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "WriteProvisionedThroughputExceeded",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "LetterChange - PutRecord.Success/PutRecords.Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "metricName": "PutRecord.Success",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "metricName": "PutRecords.Success",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "LetterChange - GetRecords.IteratorAgeMilliseconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "GetRecords.IteratorAgeMilliseconds",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "accountId": "all",
     "dimensions": { "StreamName": "${envCsi}-letter-change-stream" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "GetRecords.IteratorAgeMilliseconds",
     "namespace": "AWS/Kinesis",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  }
 ]
}