{
 "title": "SMS-Nudge Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cfDist", "label": "Cloudfront Distribution ID", "query": "*" },
   { "name": "envCsi", "label": "Environment CSI Prefix", "query": "nhs-notify-${env}-cdn" },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   { "name": "env", "label": "Environment", "query": "main" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 }, "options": { "content": "# SMS Nudge Overview" } },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Certficate Expiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "CertificateArn": "*" },
     "metricName": "DaysToExpiry",
     "namespace": "AWS/CertificateManager",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 10 }, "options": { "content": "## Traffic" } },
  {
   "title": "Ingress Events/Min",
   "type": "gauge",
   "description": "Number of Messages sent based on AWS SQS CloudWatch metrics",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Ingress DLQ",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Post Transformation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Lambda Invocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$A/60", "type": "math" },
    { "expression": "$B/60", "type": "math" }
   ]
  },
  {
   "title": "Post-Transformation DLQ",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Cloudfront Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "DistributionId": "$cfDist" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "period": "60",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    },
    { "expression": "$A/60", "type": "math" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 25 }, "options": { "content": "## Latency" } },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 11, "y": 25 }, "options": { "content": "## Errors" } },
  {
   "title": "End to End Latency",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A+$B)/1000", "type": "math" }
   ]
  },
  {
   "title": "Transformer Average Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "APIM Refresh Token Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 3, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "nhs-${env}-nudge-apim-refresh-token"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "APIM Key Generation Duration",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "nhs-${env}-nudge-apim-key-generation"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Sevice Availability",
   "type": "gauge",
   "description": "Invocations over errors for the Transformation and Processor lambdas",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100*(($A-$B)+($C-$D))/($A+$C)", "type": "math" }
   ]
  },
  {
   "title": "Lambda Errors",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "nhs-${env}-nudge-event-command-transformer"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "nhs-${env}-nudge-command-processor"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "nhs-${env}-nudge-apim-refresh-token"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "nhs-${env}-nudge-apim-key-generation"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Command Processor Avg Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "DLQ Inflow Visability",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 11, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "QueueName": "nhs-${env}-nudge-command-dlq" },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    },
    {
     "accountId": "all",
     "dimensions": {
      "QueueName": "nhs-${env}-nudge-inbound-event-dlq"
     },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cloudfront Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "$A/60", "type": "math" },
    { "expression": "$B/60", "type": "math" },
    { "expression": "$C/60", "type": "math" }
   ]
  }
 ]
}