{
 "title": "EventBus Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   { "name": "env", "label": "Environment", "query": "main" },
   { "name": "dataPlaneBusCsi", "label": "Data Plane Bus CSI", "query": "nhs-${env}-events-data-plane" },
   {
    "name": "controlPlaneBusCsi",
    "label": "Control Plane Bus CSI",
    "query": "nhs-${env}-events-control-plane"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 }, "options": { "content": "# EventBus Overview" } },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 2 }, "options": { "content": "## Traffic (Where events go)" } },
  {
   "title": "Data Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "$dataPlaneBusCsi" },
     "metricName": "MatchedEvents",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target deliveries by rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "nhs-main-events-data-plane", "RuleName": "nhs-main-events-sms-nudge" },
     "metricName": "Invocations",
     "metricQueryType": 1,
     "namespace": "AWS/Events",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/Events", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "RuleName", "type": "string" }, "type": "groupBy" },
        { "property": { "name": "EventBusName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "Invocations", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(Invocations) FROM \"AWS/Events\" GROUP BY RuleName, EventBusName",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target delivery attempts by rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "nhs-main-events-data-plane", "RuleName": "nhs-main-events-sms-nudge" },
     "metricName": "Invocations",
     "metricQueryType": 1,
     "namespace": "AWS/Events",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/Events", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "RuleName", "type": "string" }, "type": "groupBy" },
        { "property": { "name": "EventBusName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "InvocationAttempts", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(InvocationAttempts) FROM \"AWS/Events\" GROUP BY RuleName, EventBusName",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Control Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "$controlPlaneBusCsi" },
     "metricName": "MatchedEvents",
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target deliveries by rule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "nhs-main-events-data-plane", "RuleName": "nhs-main-events-sms-nudge" },
     "metricName": "Invocations",
     "metricQueryType": 1,
     "namespace": "AWS/Events",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/Events", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "RuleName", "type": "string" }, "type": "groupBy" },
        { "property": { "name": "EventBusName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "TriggeredRules", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(TriggeredRules) FROM \"AWS/Events\" GROUP BY RuleName, EventBusName",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target deliveries by rule",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 12 },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "nhs-main-events-data-plane", "RuleName": "nhs-main-events-sms-nudge" },
     "metricName": "Invocations",
     "metricQueryType": 1,
     "namespace": "AWS/Events",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/Events", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "RuleName", "type": "string" }, "type": "groupBy" },
        { "property": { "name": "EventBusName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "TriggeredRules", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(TriggeredRules) FROM \"AWS/Events\" GROUP BY RuleName, EventBusName",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target deliveries by rule",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "nhs-main-events-data-plane", "RuleName": "nhs-main-events-sms-nudge" },
     "metricName": "Invocations",
     "metricQueryType": 1,
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/Events", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "RuleName", "type": "string" }, "type": "groupBy" },
        { "property": { "name": "EventBusName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "TriggeredRules", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(TriggeredRules) FROM \"AWS/Events\" GROUP BY RuleName, EventBusName",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 20 }, "options": { "content": "## Latency" } },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 11, "y": 20 }, "options": { "content": "## Errors" } },
  {
   "title": "Put event latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "nhs-main-events-data-plane", "RuleName": "nhs-main-events-sms-nudge" },
     "metricName": "Invocations",
     "metricQueryType": 1,
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/Events", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutEventsLatency", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutEventsLatency) FROM \"AWS/Events\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Attempt Failures",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Attempt Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "100*($C+$D)/($C2+$D2)", "type": "math" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 31 }, "options": { "content": "## Saturation and Throughput" } },
  {
   "title": "Attempts per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "EventBusName": "$dataPlaneBusCsi" },
     "metricName": "InvocationAttempts",
     "metricQueryType": 1,
     "namespace": "AWS/Events",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/Events", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "EventBusName", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "InvocationAttempts", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(InvocationAttempts) FROM \"AWS/Events\" GROUP BY EventBusName ORDER BY SUM() ASC",
     "statistic": "Sum"
    }
   ]
  }
 ]
}