{
 "title": "App Response Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "envCsi", "label": "Environment CSI Prefix", "query": "nhs-${env}-response" },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   { "name": "env", "label": "Environment", "query": "main" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 }, "options": { "content": "# App Response Overview" } },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 2 }, "options": { "content": "## Response Invocations" } },
  {
   "title": "Inbound Request Events",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "QueueName": "${envCsi}-request-inbound-event-queue"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Inbound Request DLQ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "QueueName": "${envCsi}-request-inbound-event-dlq"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Request Lambda Invocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 4 },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 17, "x": 0, "y": 10 }, "options": { "content": "## Errors" } },
  {
   "title": "Request Lambda Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 12 },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "${envCsi}-request-event-command-transformer"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}