{
 "title": "Webauth Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "appId", "label": "Amplify App ID", "query": "*" },
   { "name": "envCsi", "label": "Environment CSI Prefix", "query": "nhs-notify-${env}" },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   { "name": "apiName", "label": "Composed API Name", "query": "${envCsi}-api" },
   { "name": "backupVault", "label": "Composed backup vault name", "query": "${envCsi}-backup-vault" },
   { "name": "env", "label": "Environment", "query": "main" },
   { "name": "appName", "label": "Composed API Name", "query": "${envCsi}-app" },
   { "name": "appApiName", "label": "Composed API Name", "query": "${envCsi}-app-api" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 }, "options": { "content": "# Webauth Overview" } },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 2 }, "options": { "content": "## Latency" } },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 11, "y": 2 }, "options": { "content": "## Traffic" } },
  {
   "title": "API Gateway Latency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ApiName": "$appApiName" },
     "label": "Average",
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    },
    {
     "dimensions": { "ApiName": "$appApiName" },
     "label": "Maximum",
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "API Gateway Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "ApiName": "$appApiName" },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Max Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Lambda Invocations by Function",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 15 }, "options": { "content": "## Errors" } },
  {
   "title": "API Gateway Frontend vs Backend Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "ApiName": "$appApiName" },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "ApiName": "$appApiName" },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Lambda Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 0, "y": 21 }, "options": { "content": "## Saturation" } },
  { "type": "text", "gridPos": { "h": 2, "w": 11, "x": 11, "y": 21 }, "options": { "content": "## Operational" } },
  {
   "title": "Lambda Concurency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "4xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"4xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Backup Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "BackupVaultName": "$backupVault" },
     "metricName": "NumberOfBackupJobsCompleted",
     "namespace": "AWS/Backup",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/S3", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutRequests) FROM \"AWS/S3\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$backupVault" },
     "metricName": "NumberOfBackupJobsAborted",
     "namespace": "AWS/Backup",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/S3", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutRequests) FROM \"AWS/S3\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$backupVault" },
     "metricName": "NumberOfBackupJobsFailed",
     "namespace": "AWS/Backup",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/S3", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutRequests) FROM \"AWS/S3\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "BackupVaultName": "$backupVault" },
     "metricName": "NumberOfCopyJobsFailed",
     "namespace": "AWS/Backup",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/S3", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutRequests) FROM \"AWS/S3\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Amplify Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "App": "$appId" },
     "metricName": "Requests",
     "namespace": "AWS/AmplifyHosting",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/S3", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutRequests) FROM \"AWS/S3\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "App": "$appId" },
     "metricName": "4XXErrors",
     "namespace": "AWS/AmplifyHosting",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/S3", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutRequests) FROM \"AWS/S3\"",
     "statistic": "Sum"
    },
    {
     "dimensions": { "App": "$appId" },
     "metricName": "5XXErrors",
     "namespace": "AWS/AmplifyHosting",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/S3", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "PutRequests", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(PutRequests) FROM \"AWS/S3\"",
     "statistic": "Sum"
    }
   ]
  }
 ]
}