{
 "title": "Client Callbacks Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "envCsi", "label": "Environment CSI Prefix", "query": "nhs-${env}-callbacks" },
   { "name": "datasrc", "label": "Datasource", "query": "cloudwatch" },
   { "name": "env", "label": "Environment", "query": "main" }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 }, "options": { "content": "# Client Callbacks Overview" } },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 2 }, "options": { "content": "## Callbacks Invocations" } },
  {
   "title": "Ingress Events/Min",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Lambda Invocation Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Pipe Invocations",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 10 },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "PipeName": "${envCsi}-main" },
     "metricName": "Invocations",
     "namespace": "AWS/EventBridge/Pipes",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 17 }, "options": { "content": "## Latency" } },
  {
   "title": "Pipe Overall Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "PipeName": "${envCsi}-main" },
     "metricName": "Duration",
     "namespace": "AWS/EventBridge/Pipes",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pipe Enrichment Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "PipeName": "${envCsi}-main" },
     "metricName": "EnrichmentStageDuration",
     "namespace": "AWS/EventBridge/Pipes",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pipe Target Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "PipeName": "${envCsi}-main" },
     "metricName": "TargetStageDuration",
     "namespace": "AWS/EventBridge/Pipes",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Enrichment Lambda Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "${envCsi}-client-transform-filter"
     },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Average"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 39 }, "options": { "content": "## Errors" } },
  {
   "title": "Pipe Enrichment Failure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "PipeName": "${envCsi}-main" },
     "metricName": "EnrichmentStageFailed",
     "namespace": "AWS/EventBridge/Pipes",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Pipe Target Failure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "PipeName": "${envCsi}-main" },
     "metricName": "TargetStageFailed",
     "namespace": "AWS/EventBridge/Pipes",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Pipe Execution Throttled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "PipeName": "${envCsi}-main" },
     "metricName": "ExecutionThrottled",
     "namespace": "AWS/EventBridge/Pipes",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Enrichment Lambda Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": {
      "FunctionName": "${envCsi}-client-transform-filter"
     },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "period": "60",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "sql": {
      "from": { "property": { "name": "AWS/CloudFront", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "5xxErrorRate", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(\"5xxErrorRate\") FROM \"AWS/CloudFront\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DLQ Inflow Visability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "accountId": "all",
     "dimensions": { "QueueName": "${envCsi}-inbound-event-dlq" },
     "metricName": "ApproximateNumberOfMessagesVisible",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "eu-west-2",
     "statistic": "Sum"
    }
   ]
  }
 ]
}